export default {
    "请输入环境名称，例如：test": "Please enter the environment name, for example: test",
    "请输入环境名称": "Please enter the environment name",
    "该环境已存在，请重新输入": "The environment already exists, please enter a new name",
    "保存后实时提交": "Real-time submission after saving",
    "建议单人开发使用，upload_on_save设置为true时，submit_git_before_upload无效，默认false": "Recommended for single-person development, submit_git_before_upload is invalid when upload_on_save is set to true, default is false",
    "监听文件变动": "Listen for file changes",
    "默认true，如果upload_on_save为true，则此项无效": "Default is true, this option is invalid if upload_on_save is true",
    "上传代码前提交本地git": "Commit local git before uploading code",
    "团队开发建议开启，防止覆盖远程代码": "Recommended for team development, to prevent overwriting remote code",
    "是否压缩上传，并远程解压": "Whether to compress the upload and decompress remotely",
    "账号需要支持ssh登录，系统会自动检测是否支持，不支持，则不会压缩上传": "The account needs to support SSH login, the system will automatically detect if it's supported. If not supported, it will not compress the upload",
    "上传前是否删除远程目录": "Whether to delete the remote directory before uploading",
    "上传前是否删除远程distPath配置目录，一般用于清理前端部署代码": "Whether to delete the remote distPath configuration directory before uploading, usually used to clean up front-end deployment code",
    "请选择配置（选中为true，不选为false）": "Please select the configuration (true for selected, false for unselected)",
    "已创建配置文件：sync_tools.jsonc": "Configuration file created: sync_tools.jsonc",
    "已更新配置文件：sync_tools.jsonc": "Configuration file updated: sync_tools.jsonc",
    "sync_tools.jsonc配置文件格式错误！": "Invalid format for sync_tools.jsonc configuration file!",
    "监听项目文件变动，默认true，如果upload_on_save为true，则此项无效": "Listen for project file changes, default is true, this option is invalid if upload_on_save is true",
    "请选择配置": "Please select a configuration",
    "git 提交失败，请手动提交": "Git commit failed, please commit manually",
    "请输入git提交信息": "Please enter the git commit message",
    "知道了": "Got it",
    "服务器：{0}   地址：{1}": "Server: {0}   Address: {1}",
    "服务器：{0}   地址：{1}   未上传：{2}": "Server: {0}   Address: {1}   Not uploaded: {2}",
    "打包上传": "Package and upload",
    "配置检查": "Configuration check",
    "提交Git": "Submit Git",
    "打包": "Package",
    "连接服务器": "Connect to server",
    "执行打包脚本失败 ": "Failed to execute the packaging script ",
    "压缩文件": "Compress files",
    "上传文件至服务器": "Upload files to the server",
    "删除服务器文件": "Delete server files",
    "解压服务器文件": "Decompress server files",
    "断开服务器": "Disconnect from server",
    "删除本地压缩文件": "Delete local compressed files",
    "清空缓存": "Clear cache",
    "您确定要清除所有watch缓存吗？": "Are you sure you want to clear all watch caches?",
    "确定": "Confirm",
    "取消": "Cancel",
    "失败": "Failed",
    "请配置服务端协议类型[type]，如ftp、sftp、ssh": "Please configure the server protocol type [type], such as ftp, sftp, ssh",
    "请配置用户名[username]": "Please configure the username [username]",
    "请配置服务端地址[host]": "Please configure the server address [host]",
    "请配置服务端密码或者秘钥文件路径": "Please configure the server password or private key file path",
    "请配置服务器文件目录[remotePath]": "Please configure the server file directory [remotePath]",
    "未获取到新名称！": "Failed to obtain a new name!",
    "代理连接失败，请检查配置：": "Proxy connection failed, check configuration. ",
    "准备同步": "Prepare to sync",
    "同步失败：": "Sync failed: ",
    "同步成功": "Sync successful ",
    "准备上传": "Prepare to upload",
    "正在上传：": "Uploading: ",
    "正在同步": "Syncing ",
    "正在删除：": "Deleting: ",
    "上传成功": "Upload successful ",
    "上传失败": "Upload failed ",
    "获取文件中...": "Retrieving file...",
    "正在下载：": "Downloading: ",
    "下载失败：": "Download failed: ",
    "下载完成": "Download completed"
}